# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import digtool_pb2 as digtool__pb2


class DigToolServiceStub(object):
    """The DigToolService provides DNS query functionality.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryDNS = channel.unary_unary(
                '/digtool.DigToolService/QueryDNS',
                request_serializer=digtool__pb2.DNSRequest.SerializeToString,
                response_deserializer=digtool__pb2.DNSResponse.FromString,
                )


class DigToolServiceServicer(object):
    """The DigToolService provides DNS query functionality.
    """

    def QueryDNS(self, request, context):
        """Performs a DNS query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DigToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryDNS': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryDNS,
                    request_deserializer=digtool__pb2.DNSRequest.FromString,
                    response_serializer=digtool__pb2.DNSResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'digtool.DigToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DigToolService(object):
    """The DigToolService provides DNS query functionality.
    """

    @staticmethod
    def QueryDNS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/digtool.DigToolService/QueryDNS',
            digtool__pb2.DNSRequest.SerializeToString,
            digtool__pb2.DNSResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
