# Use the Kali Linux image
FROM kalilinux/kali-rolling

# Set a faster mirror and install only necessary packages
RUN sed -i 's|http://http.kali.org/kali|http://ftp.acc.umu.se/mirror/kali.org/kali|g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-venv \
    python3-dev \
    python3-setuptools \
    build-essential \
    git \
    procps \
    dnsutils && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy only requirements first to leverage Docker caching
COPY requirements.txt .

# Create a virtual environment and install dependencies
RUN python3 -m venv venv && \
    /app/venv/bin/pip install --upgrade pip && \
    /app/venv/bin/pip install -r requirements.txt

# Copy the current directory contents into the container
COPY . .

# Expose the port gRPC will run on
EXPOSE 50051

# Run the gRPC server using the virtual environment
CMD ["/app/venv/bin/python", "server.py"]
